### PR TITLE
fix(server): types and ci typecheck

### PR DESCRIPTION
**Pull request by mhuynh5757**
This PR fixes some broken types around server auth and adds a typecheck step in the CI build.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by kpchoy — APPROVED** [review]

**Review by charliesantos — CHANGES_REQUESTED** [review]
Can you include the build command to make sure they don't fail?

**Comment by mhuynh5757** [comment]
The build command does the same thing as the typecheck command, but it generates artifacts whereas typecheck won't. Now that I think about it, we don't need typecheck if you want to remove it and just do build.

**Comment by charliesantos** [comment]
> The build command does the same thing as the typecheck command, but it generates artifacts whereas typecheck won't. Now that I think about it, we don't need typecheck if you want to remove it and just do build.

I understand. That's why we should do build because we might put more scripts as part of build.

**Comment by mhuynh5757** [comment]
I see, I'm fairly certain since
```
yarn build === tsc
yarn typecheck === tsc --noEmit
```
but better safe than sorry. I'll just do a `build` and get rid of the `typecheck`

**Review by charliesantos — APPROVED** [review]

**Pull request merged**
